name: PHP 8.2

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
          args: --prefer-dist --ignore-platform-reqs

      - name: Check code styling
        run: composer ecs-check

      - name: Create keys
        run: ./bin/create_keys

      - name: Run unit and feature tests
        run: vendor/bin/phpunit
